export const stores = [
  {
    id: 1,
    name: "Mato Grosso",
    uf: "MT",
    description: "Atuação estratégica no estado de Mato Grosso.",
    x: "40%",
    y: "38%",
    maps: "#",
  },
  {
    id: 2,
    name: "Goiás",
    uf: "GO",
    description: "Atuação estratégica no estado de Goiás.",
    x: "53%",
    y: "48%",
    maps: "#",
  },
  {
    id: 3,
    name: "Tocantins",
    uf: "TO",
    description: "Atuação estratégica no estado do Tocantins.",
    x: "58%",
    y: "33%",
    maps: "#",
  },
  {
    id: 4,
    name: "Pará",
    uf: "PA",
    description: "Atuação estratégica no estado do Pará.",
    x: "55%",
    y: "18%",
    maps: "#",
  },
  {
    id: 5,
    name: "Piauí",
    uf: "PI",
    description: "Atuação estratégica no estado do Piauí.",
    x: "72%",
    y: "30%",
    maps: "#",
  },
]